Fix for element ID gets overwritten
unipept/unipept-visualizations pull request #58
Opened 2021-03-12 08:19 UTC by pverscha

If an element ID is already set, the visualization should not overwrite it. This PR provides a fix for the bug reported in #55.

2021-03-12 09:11 UTC, bmesuere requested changes
As far as I can see, the id isn't necessary anymore and can be removed entirely.

2021-03-15 12:43 UTC, pverscha commented
ID's are no longer being used now :)

2021-03-15 15:41 UTC, bmesuere requested changes

2021-03-15 15:41 UTC, bmesuere commented on src/visualizations/heatmap/Heatmap.ts
> +            .attr("id", Math.floor(Math.random() * 2**16) + "-tooltip")
I think id's must start with a letter according to the spec

2021-04-30 09:29 UTC, bmesuere approved these changes

2021-04-30 09:29 UTC, merged